### ISSUE TITLE
编译32位DLL失败（win7平台）

### ISSUE THREAD

**Issue by xuai-xc** [jntass/TASSL-1.1.1b#1]
crypto\ec\ec_pmeth.c(230) : error C2220: 警告被视为错误 - 没有生成“object”文件

crypto\ec\ec_pmeth.c(230) : warning C4013: “SM2Kap_compute_key”未定义；假设外
部返回 int
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 10.
0\VC\BIN\cl.EXE"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Program Files (x86)\Microsoft Visual Studio 10.
0\VC\BIN\nmake.exe"”: 返回代码“0x2”
Stop.

**Comment by jntass** [comment]
去掉生成的makefile中的/WX，这个是类似linux的-Werror，把警告当做错误处理，导致编译停止。另外这个函数的定义，我们会在后续版本中声明。
