### ISSUE TITLE
`ECC-SM4-SM3:ECDHE-SM4-SM3` ，是否包含 SM2

### ISSUE THREAD

**Issue by totemofwolf** [jntass/TASSL-1.1.1b#12]
经过和 openssl-1.1.1c 对比，发现 TASSL 多了 `ECC-SM4-SM3:ECDHE-SM4-SM3` ，多实现的这部分包含 SM2么？

```
# openssl > ciphers
ECC-SM4-SM3:ECDHE-SM4-SM3
```

**Comment by jntass** [comment]
ECC-SM4-SM3:ECDHE-SM4-SM3中的EC即代表SM2.

**Comment by dyseiya** [comment]
@jntass 听说EC有 secp256r1、brainpoolP256r1等类型，我们这里面用的是哪一种呢？

**Comment by yanshichao0226** [comment]
1. ECC算法包含多种曲线，SM2只是其中的一种
2. 国密TLS1.1中定义的ECC-SM4-SM3，ECDHE-SM4-SM3等套件使用ECC算法时均强制使用SM2曲线
