### ISSUE TITLE
CNTLS_client_method会导致内存泄漏

### ISSUE THREAD

**Issue by wwwlkk** [jntass/TASSL-1.1.1b#15]
使用CNTLS_client_method建立ssl连接，在同一个进程循环建立和关闭，发现会出现内存泄漏。如果改为TLS_client_method不会出现内存泄漏。
大家有没遇到相同的问题？

**Comment by jntass** [comment]
现在已经更新了版本，可用新版的tassl-1.1.1b_R_0.8版本试试，看是否仍然有内存泄漏？
