### ISSUE TITLE
32位编译失败（win7平台）

### ISSUE THREAD

**Issue by xuai-xc** [jntass/TASSL-1.1.1b#2]
crypto \ ec \ ec_pmeth.c（230）：错误C2220：警告被视为错误 - 没有生成“object”文件

加密\ EC \ ec_pmeth.c（230）：警告C4013：“SM2Kap_compute_key”未定义;外假设
部报道查看INT 
NMAKE：致命错误U1077：““d：\程序文件（x86）\微软的Visual Studio 10 
0 \ VC \ BIN \ cl.EXE“”：返回代码“0x2” 
停止。
NMAKE：致命错误U1077：“”D：\ Program Files（x86）\ Microsoft Visual Studio 10. 
0 \ VC \ BIN \ nmake.exe“”：返回代码“0x2” 
停止。

**Comment by sysbling** [comment]
在internal/sm2.h的头文件中加上此函数的定义，然后再加入头文件就好了。

**Comment by jntass** [comment]
好的，谢谢！
