### ISSUE TITLE
tassl s_client 怎么使用 -cntls 参数

### ISSUE THREAD

**Issue by acp6** [jntass/TASSL-1.1.1b#24]
TASSL-1.1.1b移除了1.0.2版本中的s_client -cntls参数，那现在用s_client怎么指定cntls协议呢？尝试用了-cipher 'ECC-SM4-SM3:ECDHE-SM4-SM3'，但是没有用

**Comment by wuyougongzi** [comment]
新的版本没有参数，需要指定证书。也遇到改问题了，同问解决了没有

**Comment by wuyougongzi** [comment]
这个参数可以尝试直接加进去，然后忽略证书验证的过程。部分服务器可以通

**Comment by jntass** [comment]
TASSL-1.1.1b命令行s_server/s_client不支持国密SSL，可升级至TASSL-1.1.1k

下载链接https://github.com/jntass/TASSL-1.1.1k
