### ISSUE TITLE
1.1.1b版本是否不支持国密TLS1.3

### ISSUE THREAD

**Issue by dyseiya** [jntass/TASSL-1.1.1b#27]
您好，请问当前最新1.1.1b版本是否不支持国密TLS1.3？
        看贵公司网站 http://www.tass.com.cn/portal/about/news_view-58.html 的意思，好像支持国密TLS1.3了，快速迭代，江南天安做到了。我理解为贵公司走在了“GMT 0024-2014”的前面。但是使用tassl_demo的示例程序，svr和cli握手抓包，好像还是TLS1.2两次往返，并非TLS1.3的一次往返。

**Comment by yanshichao0226** [comment]
TLS1.3是支持的，国密TLS当前仅支持1.1，即 GMT 0024-2014《SSL VPN技术规范》所定义
