### ISSUE TITLE
有支持TLS V1.2吗，加密套件选什么？

### ISSUE THREAD

**Issue by minggo1981** [jntass/TASSL-1.1.1b#28]
ngix测试，tlsV1.1可以，tlsv1.2在360和密信都失败，是否已经支持tls V1.2，如果支持，加密套件应怎么写？还是需要其他配置？

**Comment by yanshichao0226** [comment]
国密TLS当前仅支持v1.1

**Comment by yanshichao0226** [comment]
国密TLS1.1是在TLS1.1的基础上结合了部分TLS1.2内容实现的，更像是一个独立的协议版本。国密TLS协议当前行标只有v1.1版本
