### ISSUE TITLE
关于不同证书链的使用

### ISSUE THREAD

**Issue by wuyougongzi** [jntass/TASSL-1.1.1b#31]
1 实际测试发现有些证书链上面上面的证书DATA_ENCIPHERMENT字段都为0，但是key_enc有值。这里面主要有两个阶段，第一个就是客户端验证签名使用的证书，tls_process_key_exchange函数里面。第二个是客户端发送加密数据给服务端，tls_construct_cke_sm2ecc里面。可能会有出错的情况，目前还没有找到标准有规定这两个阶段分别使用哪个证书。

**Comment by jntass** [comment]
tls_process_key_exchange使用签名证书；tls_construct_cke_sm2ecc使用加密证书
参考《GB/T 38636 2020》
