### ISSUE TITLE
ios静态库编译问题

### ISSUE THREAD

**Issue by 394285783** [jntass/TASSL-1.1.1b#32]
最新版本的ios静态库编译出现异常
异常代码如下：
 ssl/s3_lib.c:4748:13: error: implicit declaration of function 'ENGINE_get_pkey_meth_engine' is invalid in C99 [-Werror,-Wimplicit-function-declaration] tmp_e = ENGINE_get_pkey_meth_engine(NID_sm2);
 ^ ssl/s3_lib.c:4748:11: warning: incompatible integer to pointer conversion assigning to 'ENGINE *' (aka 'struct engine_st *') from 'int' [-Wint-conversion] tmp_e = ENGINE_get_pkey_meth_engine(NID_sm2); 
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ssl/s3_lib.c:4765:9: error: implicit declaration of function 'ENGINE_free' is invalid in C99 [-Werror,-Wimplicit-function-declaration] ENGINE_free(tmp_e); 
^ 1 warning and 2 errors generated. make[1]: *** [ssl/s3_lib.o] Error 1 make: *** [all] Error 2

编译Mac os版本10.15.6 
编译方式：
export CC="clang -arch armv7" 
export PATH="/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin:$PATH"
export CROSS_TOP=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer
export CROSS_SDK=iPhoneOS13.6.sdk
export IPHONEOS_DEPLOYMENT_TARGET=8.0
./Configure iphoneos-cross no-shared 
make

Xcode版本11.6 
使用相同方式编译官方openssl-1.1.1b可以正常编译使用。

**Comment by 0xwhatly** [comment]
我也有一样的错误，请问最后您是怎么解决的？

**Comment by wemem** [comment]
> 我也有一样的错误，请问最后您是怎么解决的？

编译最新版本吧

**Comment by orangejang** [comment]
@394285783 @wemem 找到15-ios.conf文件，将ios-common任务的disable的engine删掉。

**Comment by jntass** [comment]
可以升级TASSL-1.1.1k，已修复此问题
