### ISSUE TITLE
Win32编译过程中，碰到的一些问题。

### ISSUE THREAD

**Issue by 953349** [jntass/TASSL-1.1.1b#33]
您好，非常感谢贵公司的贡献，开发人员的辛苦努力贡献出这么优秀的开源产品，在编译过程中碰到如下问题：
编译环境：Vs 2017
编译参数：VC-WIN32 
编译版本：v1.4

编译失败，编译过程中碰到的问题：
- 报错1:  tassl_1.1.1\tassl-1.1.1b\crypto\evp\evp_enc.c(67) : warning C4715: “EVP_CipherKeygen”: 不 是所有的控件路径都返回值
- 报错2：ssl\s3_lib.c(5093): warning C4047: “=”:“void *”与“int”的间接级别不同
- 报错3：tassl-1.1.1b\ssl\ssl_rsa.c(647) : warning C4717: “SSL_set_sm2_group_id_custom”: 如递归所有控件路径，函数将导致运行时堆栈溢出。
- 报错4：ssl\t1_enc.c: warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失。
----
报错1，报错2能根据原有代码意思解决，但是报错3不知道如何处理，麻烦指点一下。
报错4打开文件修改一下文件编码即可。

**Comment by orangejang** [comment]
@953349 你好，请问你修复了这些问题了吗？我现在遇过同样的问题。

**Comment by orangejang** [comment]
已解决，将生成的makefile文件的/WX删除。

**Comment by jntass** [comment]
可升级TASSL-1.1.1k，已修复此问题
