### ISSUE TITLE
ecc cert not for signing

### ISSUE THREAD

**Issue by reclock** [jntass/TASSL-1.1.1b#35]
使用 openssl s_server -accept 4433 -CAfile cert/CA.pem -cert certs/SS.pem -cert_enc certs/SE.pem 报错：

error:140BF13E:SSL routines:ssl_set_cert:ecc cert not for signing:ssl/ssl_rsa.c:347

这个怎么解决？

**Comment by jntass** [comment]
TASSL-1.1.1b命令行s_server/s_client不支持国密SSL，同时国密SSL需要双证书/密钥

可升级至TASSL-1.1.1k， 下载链接https://github.com/jntass/TASSL-1.1.1k
