### ISSUE TITLE
win10 VS2008编译失败

### ISSUE THREAD

**Issue by dyseiya** [jntass/TASSL-1.1.1b#4]
你好，感谢贵公司提供开源国密openssl版本。我在win10上VS2013/VS2015 nmake TaSSL1.1.1b均成功。但是用VS2008 nmake报错（试了下，2008 编译openssl1.1.1b是OK的）：
ssl\statem\statem_lib.c(264) : error C2143: 语法错误 : 缺少“;”(在“类型”的前面)
ssl\statem\statem_lib.c(265) : error C2275: “EVP_MD_CTX”: 将此类型用作表达式非法

**Comment by zyxs2018** [comment]
使用vs2010 编译也有这个问题。找到错误的地方，将定义的变量 放到函数开始，就可以了。

**Comment by dyseiya** [comment]
> 使用vs2010 编译也有这个问题。找到错误的地方，将定义的变量 放到函数开始，就可以了。

谢谢zyxs2018 ，挪到函数开始的地方可以了。可能是TaSSL1.1.1b按C11风格来编的，2008和2010还不支持C11。
