### ISSUE TITLE
生成的key为PEM格式， 我需要DER格式的client.key，怎样转换？

### ISSUE THREAD

**Issue by liyuzhao** [jntass/TASSL-1.1.1b#42]

**Comment by Baymini-zx** [comment]
openssl x509 -outform der -in certificate.pem -out certificate.der

**Comment by yanshichao0226** [comment]
公钥还是私钥？ 可以使用pkey命令或者asn1parse命令
私钥PEM格式转DER：openssl pkey -inform PEM -in pri.pem -outform DER -out pri.der

**Comment by liyuzhao** [comment]
收到，多谢。
