### ISSUE TITLE
怎么没有提供SM2的终端参数？

### ISSUE THREAD

**Issue by linlih** [jntass/TASSL-1.1.1b#43]
只有sm1和sm3、sm4的？

我是直接在终端执行：openssl sm2

**Comment by yanshichao0226** [comment]
SM2曲线包含在ECC中，可以用ECC相关命令
比如生成SM2密钥：openssl ecparam -genkey -name SM2 -out sm2pri.key

**Comment by linlih** [comment]
噢噢，好的，谢谢
