### ISSUE TITLE
sm3.h   bug 

### ISSUE THREAD

**Issue by lialvin** [jntass/TASSL-1.1.1b#45]
# ifdef OPENSSL_NO_SM3

#  ifdef __cplusplus
extern "C" {
#  endif

#  error SM3 is disabled.
# endif

#  ifdef __cplusplus
}
#  endif

如果不定义 OPENSSL_NO_SM3  但是定义了 __cplusplus  ｛｝
不匹配

**Comment by jntass** [comment]
TASSL-1.1.1k已修复此问题

下载链接https://github.com/jntass/TASSL-1.1.1k
