### ISSUE TITLE
国密ECDHE-SM4-SM3算法套计算PMS流程不符合协议规定

### ISSUE THREAD

**Issue by stardrift1** [jntass/TASSL-1.1.1b#52]
https://github.com/jntass/TASSL-1.1.1b/blob/55216776253606115f1c406aaa1ea18d171c8df9/crypto/sm2/sm2_crypt.c#L685
这里协议规定ZA在前也就是服务端Z值在前面，但是代码实现是ZB在前

**Comment by jntass** [comment]
你指的哪个规范，当前ECDHE-SM4-SM3的pms流程使用的顺序，服务端Z值总是在前

**Comment by stardrift1** [comment]
> 你指的哪个规范，当前ECDHE-SM4-SM3的pms流程使用的顺序，服务端Z值总是在前



> 你指的哪个规范，当前ECDHE-SM4-SM3的pms流程使用的顺序，服务端Z值总是在前

![image](https://user-images.githubusercontent.com/42114820/143664192-2c3c5a35-b745-4ab9-8495-caa2b77aa658.png)
看代码，是先计算的客户端Z值，规范是GM/T0003.3-2012 的6.1章节

**Comment by jntass** [comment]
![image](https://user-images.githubusercontent.com/34365704/143796574-b64726a6-6ebe-4f1b-bf70-914fd980d203.png)

![1638150410(1)](https://user-images.githubusercontent.com/34365704/143796556-b54c5d1f-8229-489c-9fc6-0a6c5d96e8c9.png)
