### ISSUE TITLE
demo里根证书导入密信和360安全浏览器失败

### ISSUE THREAD

**Issue by ujshenry** [jntass/TASSL-1.1.1b#53]
我用你们定制的nginx1.16版本编译安装后，用demo里根证书配置在nginx里，密信浏览器和360浏览器可以访问，但是https上有❌❌，尝试把demo里ca根证书导入密信和360安全浏览器失败，请问怎么解决

**Comment by jntass** [comment]
正常导入证书的方式是导入到windwos中，导入SM2证书的话应该不认识，可能需要特定的方式导入。

具体可咨询浏览器厂商
