### ISSUE TITLE
请问示例程序中证书 SE.pem是做什么用的？

### ISSUE THREAD

**Issue by dyseiya** [jntass/TASSL-1.1.1b#7]
你好，请问示例程序 Tassl_demo\cert\certs 里服务器证书有 SS.pem和SE.pem，SE.pem是如何使用的？
个人理解SS是服务器证书，SE是服务器加密证书。服务器证书好理解，TLS握手时认证用。加密证书需要吗？加密时应该是用协商出来会话密钥来进行加密通信吧，感觉不需要什么加密证书。
客户端的CS.pem和CE.pem也是类似情况。
运行示例程序，如果去掉某个证书的校验，后面会握手失败。

**Comment by zyxs2018** [comment]
国密要求使用双证书，SS是服务器签名证书，SE是服务器加密证书。

**Comment by dyseiya** [comment]
> 国密要求使用双证书，SS是服务器签名证书，SE是服务器加密证书。

感谢解答 ^_^
