### ISSUE TITLE
说好的函数 都没有实现呢

### ISSUE THREAD

**Issue by zyxs2018** [jntass/TASSL-1.1.1b#8]
SSL_CTX_use_enc_PrivateKey_ASN1()、SSL_use_enc_PrivateKey_file() 这些函数在新版本1.1.1b里面没有封装，上一个版本1.0.2里面都有，希望管理员检查并提交下遗漏的部分代码。

**Comment by jntass** [comment]
TASSL-1.1.1k可直接使用原生openssl函数加载加密证书/密钥

下载链接https://github.com/jntass/TASSL-1.1.1k
